graph TD

    CRMBookingFlow{CRMBookingFlow}-->Ft_listProcessedWorkOrderEC

    Ft_listProcessedWorkOrderEC[(Tacdis)]-->|"(Processed work orders)"|SendGrid

    SendGrid{{SendGrid}}-->|"(Template id based on technician group or location)"|Email

    Email-->To

    To-->|"(valid email found)"|Driver

    To-->|"(no valid email found)"|Technician

    Email-->BCC

    Email-->|"Report email sent"|CRMDataImport[(Volvo Bil)]
